language: generic
sudo : required
services :
  - docker

before_install :
  - docker build -t 7682080176/docker-kubernetes-react-poc -f Dockerfile.dev .

script :
  - docker run -e CI=true 7682080176/docker-kubernetes-react-poc npm run test -- --coverage

deploy :
  provider : elasticbeanstalk
  region : "ap-south-1"
  app : "docker-react-poc"
  env : "Dockerreactpoc-env"
  bukcet_name : "elasticbeanstalk-ap-south-1-179250594100"
  bukcket_path : "docker-react-poc"
  on:
    branch : master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  


