language: generic
sudo : required
services :
  - docker

before_install :
  - docker build -t 7682080176/docker-kubernetes-react-poc -f Dockerfile.dev .

script :
  - docker run -e CI=true U7682080176/docker-kubernetes-react-poc npm run test -- --coverage