sudo: required
services:
  - docker

before_install:
  - docker build -t 7682080176/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 7682080176/react-test npm test -- --coverage

after_success:
  - docker build -t 7682080176/multi-client ./client
  - docker build -t 7682080176/multi-nginx ./nginx
  - docker build -t 7682080176/multi-server ./server
  - docker build -t 7682080176/multi-worker ./worker